apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: REPLACE_TAG
spec:
  template:
    spec:
      containers:
        - image: REPLACE_REGISTRY:REPLACE_TAG
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz