apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_TAG
  namespace: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=s3://REPLACE_BUCKET/REPLACE_CONTEXT_PATH"
        - "--destination=REPLACE_REGISTRY:REPLACE_TAG"
        - "--skip-tls-verify"
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-storage-secret
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-storage-secret
              key: secret-access-key
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: s3-storage-secret
              key: endpoint 
        - name: AWS_REGION
          value: "apac"
        - name: S3_FORCE_PATH_STYLE
          value: "true"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret