services:
  postgres:
    image: "postgres:17-alpine"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Run a command after the container starts to create the test database
      - ./scripts/create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
volumes:
  postgres_data: {}
