[project]
name = "faas-platform"
version = "0.1.0"
description = "Function as a Service Platform"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "jinja2>=3.1.6",
    "kubernetes>=32.0.1",
]
