[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.13",
    "fastapi[standard]>=0.115.12",
    "jinja2>=3.1.6",
    "kubernetes>=32.0.1",
]
