// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  CreateFunctionFunctionsLanguagePostData,
  CreateFunctionFunctionsLanguagePostResponse,
} from "./types.gen"

export class DefaultService {
  /**
   * Create Function
   * @param data The data for the request.
   * @param data.language
   * @returns Function Successful Response
   * @throws ApiError
   */
  public static createFunctionFunctionsLanguagePost(
    data: CreateFunctionFunctionsLanguagePostData,
  ): CancelablePromise<CreateFunctionFunctionsLanguagePostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/functions/{language}",
      path: {
        language: data.language,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}
