// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  CreateFunctionFunctionsPostData,
  CreateFunctionFunctionsPostResponse,
  DeleteFunctionFunctionsFunctionIdDeleteData,
  DeleteFunctionFunctionsFunctionIdDeleteResponse,
} from "./types.gen"

export class DefaultService {
  /**
   * Create Function
   * @param data The data for the request.
   * @param data.requestBody
   * @returns FunctionResponse Successful Response
   * @throws ApiError
   */
  public static createFunctionFunctionsPost(
    data: CreateFunctionFunctionsPostData,
  ): CancelablePromise<CreateFunctionFunctionsPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/functions/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Function
   * @param data The data for the request.
   * @param data.functionId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteFunctionFunctionsFunctionIdDelete(
    data: DeleteFunctionFunctionsFunctionIdDeleteData,
  ): CancelablePromise<DeleteFunctionFunctionsFunctionIdDeleteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/functions/{function_id}",
      path: {
        function_id: data.functionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}
