// This file is auto-generated by @hey-api/openapi-ts

export type FunctionCreate = {
  language: string
  body: string
}

export type FunctionResponse = {
  id: string
  language: string
  url: string
  created_at: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type CreateFunctionFunctionPostData = {
  requestBody: FunctionCreate
}

export type CreateFunctionFunctionPostResponse = FunctionResponse

export type DeleteFunctionFunctionFunctionIdDeleteData = {
  functionId: string
}

export type DeleteFunctionFunctionFunctionIdDeleteResponse = unknown
