// This file is auto-generated by @hey-api/openapi-ts

/**
 * Represents a serverless function
 */
export type Function = {
  id: string
  language: string
  created_at: string
  url: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type CreateFunctionFunctionsLanguagePostData = {
  language: string
}

export type CreateFunctionFunctionsLanguagePostResponse = Function
