{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "faas-platform.fullname" . }}-migrate
  labels:
    app.kubernetes.io/name: {{ include "faas-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "faas-platform.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "faas-platform.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          {{- $secretName := "" -}}
          {{- if .Values.secrets.existingSecret }}
          {{- $secretName = .Values.secrets.existingSecret -}}
          {{- else if and .Values.secrets.create .Values.secrets.name }}
          {{- $secretName = .Values.secrets.name -}}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "faas-platform.fullname" . }}-env
            {{- if $secretName }}
            - secretRef:
                name: {{ $secretName }}
            {{- end }}
          command: ["python", "-m", "src.db_migrate", "upgrade", "head"]
{{- end }}
