{{- if .Values.ciliumEgress.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "faas-platform.fullname" . }}-egress
  namespace: {{ .Values.namespace.functions | default "functions" | quote }}
spec:
  # Apply to all pods in the functions namespace. If you want a narrower match,
  # add labels to function pods and replace endpointSelector with matchLabels.
  endpointSelector: {}
  egress:
    - toFQDNs:
{{- range .Values.ciliumEgress.allowedDomains }}
        - matchName: {{ . | quote }}
{{- end }}
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: "/"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: {{ .Values.ciliumEgress.dnsSelector }}
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
{{- end }}
