apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-api
  namespace: faas-app
  labels:
    app.kubernetes.io/name: faas-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: faas-api
  template:
    metadata:
      labels:
        app: faas-api
    spec:
      serviceAccountName: faas-api-service-account
      containers:
      - name: faas-api
        image: ghcr.io/tk-hap/faas_platform:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: env-secrets
        - configMapRef:
            name: env-configmap
