apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faas-api-functions-binding
  namespace: functions
subjects:
  - kind: ServiceAccount
    name: faas-api-service-account
    namespace: faas-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-api-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faas-api-kaniko-binding
  namespace: kaniko
subjects:
  - kind: ServiceAccount
    name: faas-api-service-account
    namespace: faas-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-api-access